import { defineConfig, devices } from "@playwright/test";

function requiredEnvironment(name: string): string {
  const value = process.env[name]?.trim();
  if (!value) throw new Error(`${name} must be generated by run-ui-journeys.ps1`);
  return value;
}

const rendererUrl = "http://127.0.0.1:1420";
const mockSidecarUrl = "http://127.0.0.1:43129";

export default defineConfig({
  testDir: "./tests/ui",
  outputDir: "./test-results",
  timeout: 30_000,
  expect: { timeout: 5_000 },
  fullyParallel: false,
  forbidOnly: Boolean(process.env.CI),
  retries: process.env.CI ? 1 : 0,
  workers: 1,
  reporter: process.env.CI
    ? [["line"]]
    : [["list"], ["html", { open: "never" }]],
  use: {
    baseURL: rendererUrl,
    trace: "retain-on-failure",
    screenshot: "only-on-failure",
    video: "off",
  },
  webServer: {
    command: "npm run test:ui:serve",
    url: rendererUrl,
    reuseExistingServer: false,
    timeout: 120_000,
    env: {
      VITE_API_URL: mockSidecarUrl,
      VITE_API_BOOTSTRAP_SECRET: requiredEnvironment("UI_TEST_BOOTSTRAP_SECRET"),
      VITE_API_INSTANCE_ID: "playwright-isolated-renderer",
    },
  },
  projects: [
    {
      name: "chromium-renderer",
      use: { ...devices["Desktop Chrome"] },
    },
  ],
});
